create metods servicesController
jfelipeq14/hermes-node pull request #11
Opened 2024-09-04 12:21 UTC by Andrey0108

2024-09-07 20:04 UTC, jfelipeq14 requested changes
En todos los schemas (model) falta la exportacion de la clase

2024-09-07 20:04 UTC, jfelipeq14 commented on src/models/role/role.model.js
> +    const data = await roleSchema.find().pretty()
¿Te funciona el .pretty()? Generalmente hay error con el y más si no se exporta la clase como debe ser

2024-09-07 20:04 UTC, jfelipeq14 commented on src/models/services/services.model.js
> +    const data = await servicesSchema.find().pretty()
Lo mismo del pretty

2024-09-10 12:32 UTC, Andrey0108 commented on src/models/services/services.model.js
> +    const data = await servicesSchema.find().pretty()
Ya resuelto

2024-09-10 22:55 UTC, merged